apiVersion: apps/v1
kind: Deployment
metadata:
    name: adservice-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
        app: adservice
  template:
    metadata: 
      labels: 
        app: adservice
    spec: 
      containers: 
       - name: adservice
         image: jothamcloud/adservice:latest
         ports:
         - containerPort: 9555 
         env: 
          - name: PORT
            value: "9555"
---
apiVersion: v1
kind: Service
metadata: 
   name: adservice
spec:
  type: ClusterIP
  ports:
  - port: 9555
    targetPort: 9555
  selector:
    app: adservice

