apiVersion: apps/v1
kind: Deployment
metadata:
    name: checkoutservice-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
        app: checkoutservice
  template:
    metadata: 
      labels: 
        app: checkoutservice
    spec: 
      containers: 
       - name: checkoutservice
         image: jothamcloud/checkoutservice:3
         ports:
         - containerPort: 5050 
         env: 
          - name: PORT
            value: "5050"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice:3550"
          - name: CURRENCY_SERVICE_ADDR
            value: "currencyservice:7000"
          - name: CART_SERVICE_ADDR
            value: "cartservice:7070"
          - name: PAYMENT_SERVICE_ADDR
            value: "paymentservice:50051"
          - name: SHIPPING_SERVICE_ADDR
            value: "shippingservice:50051"
          - name: EMAIL_SERVICE_ADDR
            value: "emailservice:4000"
          # - name: GOTRACEBACK
          #   value: single
---      
apiVersion: v1
kind: Service
metadata: 
   name: checkoutservice
spec:
  type: ClusterIP
  ports:
  - port: 5050
    targetPort: 5050
  selector:
    app: checkoutservice

