apiVersion: apps/v1
kind: Deployment
metadata:
    name: emailservice-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
        app: emailservice
  template:
    metadata: 
      labels: 
        app: emailservice
    spec: 
      containers: 
       - name: emailservice
         image: jothamcloud/emailservice:3
         ports:
         - containerPort: 8080 
         env: 
          - name: PORT
            value: "8080"
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: DISABLE_PROFILER
            value: "1"
          - name: DISABLE_TRACING
            value: "1"
---
apiVersion: v1
kind: Service
metadata: 
   name: emailservice
spec:
  type: ClusterIP
  ports:
  - port: 4000
    targetPort: 8080
  selector:
    app: emailservice

