apiVersion: apps/v1
kind: Deployment
metadata:
    name: loadgenerator-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
        app: loadgenerator
  template:
    metadata: 
      labels: 
        app: loadgenerator
    spec: 
      containers: 
       - name: loadgenerator
         image: jothamcloud/loadgenerator:4
         ports:
         - containerPort: 8080 
         env: 
          - name: FRONTEND_ADDR
            value: "frontend:80"
          - name: USERS
            value: "10"
          - name: GEVENT_SUPPORT
            value: "true"
