apiVersion: apps/v1
kind: Deployment
metadata:
    name: shippingservice-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
        app: shippingservice
  template:
    metadata: 
      labels: 
        app: shippingservice
    spec: 
      containers: 
       - name: shippingservice
         image: jothamcloud/shippingservice:3
         ports:
         - containerPort: 50051 
         env: 
          - name: PORT
            value: "50051"
          - name: GOTRACEBACK
            value: "single"
---
apiVersion: v1
kind: Service
metadata: 
   name: shippingservice
spec:
  type: ClusterIP
  ports:
  - port: 50051
    targetPort: 50051
  selector:
    app: shippingservice

